languageCode = "en-us"
title = "Dopetrope"
baseURL = "https://5izl.top/"
theme = "dopetrope"

[params.portfolio]
    title = "My Portfolio"
    foldername = "portfolio"
    findoutmoretext = "Find out more"

[params.blog]
    title = "The Blog"
    viewalltext = "View All"
    foldername = "blog"

[params.settings]
    googleanalytics = "UA-113904582-2"
    disqus = "hugo-dopetrope"
